apiVersion: v1
kind: Service
metadata:
   name: polling-app-mysql
   labels:
     app: polling-app
spec:
   type: ClusterIP 
   selector:
      app: polling-app
      tier: mysql
   ports:
   - targetPort: 3306
     port: 32768
                    


