apiVersion: v1
kind: Service
metadata:
   name: polling-app-server
   labels:
      app: polling-app-server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
      app: polling-app-server

