apiVersion: v1
kind: Service
metadata:
   name: polling-app-server
   labels:
      app: polling-app-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
      app: polling-app-server

