apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv
spec:
   storageClassName: mysql-fast
   accessModes:
   - ReadWriteOnce
   capacity:
      storage: 5Gi
   awsElasticBlockStore:
     fsType: ext4
     volumeID: vol-0100f42d1e956348e
