apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv
spec:
   storageClassName: mysql-fast
   accessModes:
   - ReadWriteOnce
   capacity:
      storage: 4Gi
   awsElasticBlockStore:
     fsType: ext4
     volumeID: vol-0cccb87e5bcfa028a
